title: Minimal theme
description: Minimal is a theme for GitHub Pages.
show_downloads: true
google_analytics:
theme:

sass:
  sass_dir:         _sass
  style:            :compressed

markdown: kramdown
gems: [bootstrap, autoprefixer-rails, jekyll-assets, jekyll-paginate, jekyll-gist]
